version: 2 # use CircleCI 2.0
orbs:
  codecov: codecov/codecov@1.0.2
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/ps-acl # directory where steps will run
    docker:
      - image: circleci/node:11.1.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - codecov/upload:
        - file: ./coverage/coverage-final.json
      - store_artifacts:
          path: test-results.xml
          prefix: tests